Models/Emprunter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Database_First.Models
{
    public partial class Emprunter
    { 
        public int IdE { get; set; }
        public int? IdM { get; set; }
        public int? IdL { get; set; }

        [DataType(DataType.Date)]
        public DateTime? DateEmp { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateRetour { get; set; }

        public virtual Livre IdLNavigation { get; set; }
        public virtual Membre IdMNavigation { get; set; }
    }
}

Controllers/EmpruntersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Database_First.Models;

namespace Database_First.Controllers
{
    public class EmpruntersController : Controller
    {
        private readonly bdgplccContext _context;
          
        public EmpruntersController(bdgplccContext context)
        {
            _context = context;
        }

        // GET: Emprunters
        public async Task<IActionResult> Index()
        {
            var bdgplccContext = _context.Emprunters.Include(e => e.IdLNavigation).Include(e => e.IdMNavigation);
            return View(await bdgplccContext.ToListAsync());
        }
           
        // GET: Emprunters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprunter = await _context.Emprunters
                .Include(e => e.IdLNavigation)
                .Include(e => e.IdMNavigation)
                .FirstOrDefaultAsync(m => m.IdE == id);
            if (emprunter == null)
            {
                return NotFound();
            }

            return View(emprunter);
        }

        // GET: Emprunters/Create
        public IActionResult Create()
        {
            ViewData["IdL"] = new SelectList(_context.Livres, "IdL", "IdL");
            ViewData["IdM"] = new SelectList(_context.Membres, "IdM", "IdM");
            return View();
        }

        // POST: Emprunters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdE,IdM,IdL")] Emprunter emprunter)
        {
            if (ModelState.IsValid)
            {

                int nbEmprunts = _context.Emprunters.Where(p => p.IdM  == emprunter.IdM  && p.DateRetour == null).Count();
                if (nbEmprunts >= 3)
                {
                    ViewBag.Message = "Vous avez atteint votre limite d'emprunts! Veuillez retourner les livres avant d'effectuer un autre emprunt";
                    return View("Erreur");
                }

                DateTime DateEmp = DateTime.Today;
                emprunter.DateEmp = DateEmp; 

                _context.Add(emprunter);



                var livre = _context.Find<Livre>(emprunter.IdL); 
                if (livre.NbExemlpaireTotal > 0 )
                {
                    livre.NbExemlpaireTotal--;
                   _context.Update<Livre>(livre);
                } else
                {
                    ViewBag.Message = "Ce livre n'est pas disponible pour le moment. *Merci pour votre compréhension* ";
                    return View("Erreur");
                }
                

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdL"] = new SelectList(_context.Livres, "IdL", "IdL", emprunter.IdL); 
            ViewData["IdM"] = new SelectList(_context.Membres, "IdM", "IdM", emprunter.IdM);
            return View(emprunter);
        }

        // GET: Emprunters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprunter = await _context.Emprunters.FindAsync(id);
            if (emprunter == null)
            {
                return NotFound();
            }
            ViewData["IdL"] = new SelectList(_context.Livres, "IdL", "IdL", emprunter.IdL);
            ViewData["IdM"] = new SelectList(_context.Membres, "IdM", "IdM", emprunter.IdM);
            return View(emprunter);
        }

        // POST: Emprunters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdE,IdM,IdL,DateEmp,DateRetour")] Emprunter emprunter)
        {
            if (id != emprunter.IdE)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emprunter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmprunterExists(emprunter.IdE))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdL"] = new SelectList(_context.Livres, "IdL", "IdL", emprunter.IdL);
            ViewData["IdM"] = new SelectList(_context.Membres, "IdM", "IdM", emprunter.IdM);
            return View(emprunter);
        }

        // GET: Emprunters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprunter = await _context.Emprunters
                .Include(e => e.IdLNavigation)
                .Include(e => e.IdMNavigation)
                .FirstOrDefaultAsync(m => m.IdE == id);
            if (emprunter == null)
            {
                return NotFound();
            }

            return View(emprunter);
        }

        // POST: Emprunters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var emprunter = await _context.Emprunters.FindAsync(id);
            _context.Emprunters.Remove(emprunter);


            var livre = _context.Find<Livre>(emprunter.IdL);

            if(emprunter.DateRetour == null)
            {
                livre.NbExemlpaireTotal++;
                _context.Update<Livre>(livre);
            }

                      

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> EffectuerRetour(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var emprunter = await _context.Emprunters
                .Include(p => p.IdLNavigation)
                .Include(p => p.IdMNavigation)
                .FirstOrDefaultAsync(m => m.IdE  == id);


             DateTime dateRetour = DateTime.Today;

            TimeSpan  nbJours  = (TimeSpan)(dateRetour - emprunter.DateEmp);

             //var nbJours = 3; 

            //int nbJours = (int)(dateRetour - emprunter.DateEmp).Days; 


            if (nbJours.Days > 7)
            {

                ViewBag.Message = "Vous avez dépassé la période indiquée (7 jours), veuillez contacter l'administration ";
                return View("Erreur");
            }
            emprunter.DateRetour = dateRetour;
            _context.Update<Emprunter>(emprunter);


            var livre = _context.Find<Livre>(emprunter.IdL);
            livre.NbExemlpaireTotal++; 
            _context.Update<Livre>(livre);


            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }










        private bool EmprunterExists(int id)
        {
            return _context.Emprunters.Any(e => e.IdE == id);
        }
    }
}

Controllers/LivresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks; 
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Database_First.Models;

namespace Database_First.Controllers
{
    public class LivresController : Controller
    {
        private readonly bdgplccContext _context;

        public LivresController(bdgplccContext context)
        {
            _context = context;
        }

        // GET: Livres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Livres.ToListAsync());
        }

        public async Task<IActionResult> Afficherlivres(String trouverlivre)
        {
            if (trouverlivre == null)
            {
                return RedirectToAction("Index");

            }
            return View("Index", await _context.Livres.Where(m => m.Titre.Contains(trouverlivre)).ToListAsync());
        }

        // GET: Livres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres
                .FirstOrDefaultAsync(m => m.IdL == id);
            if (livre == null)
            {
                return NotFound();
            }

            return View(livre);
        }

        // GET: Livres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdL,Titre,Auteur,Categories,NbExemlpaire,NbExemlpaireTotal")] Livre livre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(livre);
        }

        // GET: Livres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres.FindAsync(id);
            if (livre == null)
            {
                return NotFound();
            }
            return View(livre);
        }

        // POST: Livres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdL,Titre,Auteur,Categories,NbExemlpaire,NbExemlpaireTotal")] Livre livre)
        {
            if (id != livre.IdL)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivreExists(livre.IdL))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livre);
        }

        // GET: Livres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres
                .FirstOrDefaultAsync(m => m.IdL == id);
            if (livre == null)
            {
                return NotFound();
            }

            return View(livre);
        }

        // POST: Livres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livre = await _context.Livres.FindAsync(id);
            _context.Livres.Remove(livre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivreExists(int id)
        {
            return _context.Livres.Any(e => e.IdL == id);
        }
    }
}

Controllers/MembresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Database_First.Models;

namespace Database_First.Controllers 
{
    public class MembresController : Controller
    {
        private readonly bdgplccContext _context;

        public MembresController(bdgplccContext context)
        {
            _context = context;
        }

        // GET: Membres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Membres.ToListAsync());
        }

        // GET: Membres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .FirstOrDefaultAsync(m => m.IdM == id);
            if (membre == null)
            {
                return NotFound();
            }

            return View(membre);
        }

        // GET: Membres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Membres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdM,Nom,Prenom,Courriel,MotPasse")] Membre membre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(membre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(membre);
        }

        // GET: Membres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres.FindAsync(id);
            if (membre == null)
            {
                return NotFound();
            }
            return View(membre);
        }

        // POST: Membres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdM,Nom,Prenom,Courriel,MotPasse")] Membre membre)
        {
            if (id != membre.IdM)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembreExists(membre.IdM))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(membre);
        }

        // GET: Membres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .FirstOrDefaultAsync(m => m.IdM == id);
            if (membre == null)
            {
                return NotFound();
            }

            return View(membre);
        }

        // POST: Membres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var membre = await _context.Membres.FindAsync(id);
            _context.Membres.Remove(membre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembreExists(int id)
        {
            return _context.Membres.Any(e => e.IdM == id);
        }
    }
}

Views/Emprunters/Create.cshtml
@model Database_First.Models.Emprunter
<link rel="stylesheet" href="~/css/CEmprunter.css">

@{
    ViewData["Title"] = "Create";
}


<div class="form-horizontal fromcreate">

    <h1>Emprunter un livre</h1>
    <hr />
    <div class="row">
        <div class="col-md-8">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="IdM" class="control-label"></label>
                    <select asp-for="IdM" class="form-control" asp-items="ViewBag.IdM"></select>
                </div>
                <div class="form-group">
                    <label asp-for="IdL" class="control-label"></label>
                    <select asp-for="IdL" class="form-control" asp-items="ViewBag.IdL"></select>
                </div>
                @*<div class="form-group">
                    <label asp-for="DateEmp" class="control-label"></label>
                    <input asp-for="DateEmp" class="form-control" />
                    <span asp-validation-for="DateEmp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateRetour" class="control-label"></label>
                    <input asp-for="DateRetour" class="form-control" />
                    <span asp-validation-for="DateRetour" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <input type="submit" value="Envoyer" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<span>
    <a asp-action="Index">
        <i class="fas fa-arrow-circle-left fa-4x"> </i>

    </a>
</span>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Emprunters/Delete.cshtml
@model Database_First.Models.Emprunter

@{
    ViewData["Title"] = "Delete";
}

 
<h3>Êtes-vous sûr de vouloir supprimer ce prêt</h3>
<div>
    <h4>Prêt</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.DateEmp)*@
            Date de prêt
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateEmp)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.DateRetour)*@
            Date de retour 
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateRetour)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.IdLNavigation)*@
            Id- Livre
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdLNavigation.IdL)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.IdMNavigation)*@
            Id- Membre
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdMNavigation.IdM)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="IdE" />
        @*<input type="submit" value="Supprimer " class="btn btn-danger" /> |  <a asp-action="Index"><i class="fas fa-arrow-alt-circle-left fa-3x"></i></a>&nbsp;&nbsp;*@

        <input type="submit" value="Oui" class="btn btn-danger" /> | <a asp-action="Index" class="btn btn-primary">  Non </a>&nbsp;&nbsp;


    </form>
  

</div>

Views/Emprunters/Details.cshtml
@model Database_First.Models.Emprunter

@{
    ViewData["Title"] = "Details";
}

<h1>Détails</h1>

<div>
    <h4>Emprunter</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.DateEmp)*@
            Date de prêt

        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEmp)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.DateRetour)*@
           Date de retour 

        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateRetour)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.IdLNavigation)*@
            Id-Livre
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdLNavigation.IdL)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.IdMNavigation)*@
            Id-Membre

        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdMNavigation.IdM)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index"><i class="fas fa-arrow-alt-circle-left"></i></a>&nbsp;&nbsp;

    <a asp-action="Edit" asp-route-id="@Model.IdE"> <i class="fas fa-edit"></i></a> |
 
</div>

Views/Emprunters/Edit.cshtml
@model Database_First.Models.Emprunter

@{
    ViewData["Title"] = "Edit";
}
 

<h4>Emprunter</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdE" />
            <div class="form-group">
                <label  class="control-label"> Id- Membre</label>
                <select asp-for="IdM" class="form-control" asp-items="ViewBag.IdM"></select>
                <span asp-validation-for="IdM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label"> Id- Livre</label>
                <select asp-for="IdL" class="form-control" asp-items="ViewBag.IdL"></select>
                <span asp-validation-for="IdL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Date de prêt</label>
                <input asp-for="DateEmp" class="form-control" />
                <span asp-validation-for="DateEmp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Date de retour</label>
                <input asp-for="DateRetour" class="form-control" />
                <span asp-validation-for="DateRetour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<span>
    <a asp-action="Index">
        <i class="fas fa-arrow-circle-left fa-4x"> </i>

    </a>
</span>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Emprunters/Erreur.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>@ViewBag.Message</h1>

<a asp-action="Index">
    <i class="fas fa-arrow-circle-left fa-4x"> </i>
</a>

Views/Emprunters/Index.cshtml
@model IEnumerable<Database_First.Models.Emprunter>
    <link rel="stylesheet" href="~/css/IndexEmprunter.css" />

    @{
        ViewData["Title"] = "Index";
    }
<div  > 
    <h1 id="titre1">Les prêts</h1>
</div>
<div class="divlistprets">


    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.DateEmp)*@
                    Date de prêt
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.DateRetour)*@
                    Date de retour
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.IdLNavigation)*@
                    Id-Livre
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.IdMNavigation)*@
                    Id-Membre
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateEmp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateRetour)
                </td>
                <td>
                    <a asp-controller="Livres"
                       asp-action="Details" asp-route-id="@item.IdLNavigation.IdL" >    @Html.DisplayFor(modelItem => item.IdLNavigation.IdL) </a>
                </td>
                <td>
                    <a asp-controller="Membres"
                       asp-action="Details" asp-route-id="@item.IdMNavigation.IdM" > @Html.DisplayFor(modelItem => item.IdMNavigation.IdM)  </a>
                </td>
                <td>
                    <a asp-action="EffectuerRetour" asp-route-id="@item.IdE">Retour <i class="fas fa-book"></i></a>&nbsp;&nbsp;

                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdE"><i class="fas fa-edit"></i> </a>&nbsp;&nbsp;
                    <a asp-action="Details" asp-route-id="@item.IdE"><i class="fas fa-info"></i></a>&nbsp;&nbsp;
                    <a asp-action="Delete" asp-route-id="@item.IdE"><i class="fas fa-trash-alt"></i> </a>

                </td>


            </tr>
            }
        </tbody> 
    </table>
</div> 
    <button type="button" class="btn btn-success">
        <h4> <a asp-action="Create">Ajouter un prêt</a>     </h4>
    </button>